format_version: 2
environments:
  test:
    pipelines:
      - poc-build
      - poc-provisioning
      - poc-infra-destroy

pipelines:
  poc-build:
    group: poc
    label_template: "${mygit[:8]}"
    lock_behavior: none
    materials:
      mygit:
        git: https://github.com/singals/gocd-poc.git
        branch: master
    stages: # list of stages in order
      - build:
          fetch_material: yes
          keep_artifacts: yes
          environment_variables:
              PHASE: build
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - sh main.sh build
      - test:
          fetch_material: yes
          keep_artifacts: yes
          environment_variables:
            PHASE: test
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - node src/test/test.js

  poc-provisioning:
    group: infra
    label_template: "${mygit[:8]}"
    materials:
      mygit:
        git: https://github.com/singals/gocd-poc.git
        branch: master
      myupstream:
        type: dependency
        pipeline: poc-build
        stage: test
    stages: # list of stages in order
      - provision:
          fetch_material: yes
          keep_artifacts: yes
          jobs:
            provisioning:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - sh provision.sh create


  poc-infra-destroy:
      group: infra
      label_template: "${mygit[:8]}"
      materials:
        mygit:
          git: https://github.com/singals/gocd-poc.git
          branch: master
        myupstream:
          type: dependency
          pipeline: poc-provisioning
          stage: provision
      stages: # list of stages in order
        - destroy:
            fetch_material: yes
            keep_artifacts: yes
            jobs:
              destroy-infra:
                tasks:
                  - exec:
                      command: bash
                      arguments:
                        - -c
                        - sh provision.sh destroy
# Add pipelines to deploy the app to demo env