format_version: 2
environments:
  test:
    pipelines:
      - poc-build
#      - poc-deploy

pipelines:
  poc-build:
    group: poc
    label_template: "${mygit[:8]}"
    lock_behavior: none
    materials:
      mygit:
        git: https://github.com/singals/gocd-poc.git
        branch: master
#      myupstream:
        # type: dependency
#        pipeline: pipe2
#        stage: test
    stages: # list of stages in order
      - build:
          fetch_material: yes
          keep_artifacts: yes
          environment_variables:
              PHASE: build
          jobs:
            run:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - sh main.sh build
      - test:
          fetch_material: yes
          keep_artifacts: yes
          environment_variables:
            PHASE: test
          jobs:
            run:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - node src/test/test.js

# Replace dummy tasks and add for node.js
# Add pipelines to deploy the app to demo env